CREATE TABLE DEV.CUSTOMERS AS
SELECT 
    C_CUSTKEY,
    C_NAME,
    C_ADDRESS,
    C_NATIONKEY,
    C_PHONE,
    C_ACCTBAL
FROM DEV.RAW_CUSTOMERS;

CREATE TABLE DEV.ORDERS AS
SELECT 
    O_ORDERKEY,
    O_CUSTKEY,
    O_ORDERSTATUS,
    O_TOTALPRICE,
    O_ORDERDATE
FROM DEV.RAW_ORDERS;
