CREATE TABLE DEV.SALES_SUMMARY AS
SELECT 
    C.C_NAME AS CUSTOMER_NAME,
    COUNT(O.O_ORDERKEY) AS TOTAL_ORDERS,
    SUM(O.O_TOTALPRICE) AS TOTAL_SPENT
FROM DEV.CUSTOMERS C
JOIN DEV.ORDERS O ON C.C_CUSTKEY = O.O_CUSTKEY
GROUP BY C.C_NAME;
